### ISSUE TITLE
[lutaml-model Conversion] Error when running specs

### ISSUE THREAD

**Issue by kwkwan** [lutaml/xmi#46]
```
 NoMethodError:
       undefined method `item_order' for "thecustomprofile":String
     
                   instance.element_order = doc.item_order
                                               ^^^^^^^^^^^
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/serialize.rb:287:in `apply_xml_mapping'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/serialize.rb:237:in `apply_mappings'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/attribute.rb:65:in `cast'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/serialize.rb:311:in `block in apply_xml_mapping'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/serialize.rb:291:in `each'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/serialize.rb:291:in `apply_xml_mapping'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/serialize.rb:237:in `apply_mappings'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/attribute.rb:65:in `cast'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/serialize.rb:311:in `block in apply_xml_mapping'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/serialize.rb:291:in `each'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/serialize.rb:291:in `apply_xml_mapping'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/serialize.rb:237:in `apply_mappings'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/attribute.rb:65:in `cast'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/serialize.rb:311:in `block in apply_xml_mapping'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/serialize.rb:291:in `each'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/serialize.rb:291:in `apply_xml_mapping'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/serialize.rb:237:in `apply_mappings'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/attribute.rb:65:in `cast'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/serialize.rb:311:in `block in apply_xml_mapping'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/serialize.rb:291:in `each'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/serialize.rb:291:in `apply_xml_mapping'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/serialize.rb:237:in `apply_mappings'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/attribute.rb:65:in `cast'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/serialize.rb:311:in `block in apply_xml_mapping'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/serialize.rb:291:in `each'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/serialize.rb:291:in `apply_xml_mapping'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/serialize.rb:237:in `apply_mappings'
     # ~/src/lutaml/lutaml-model/lib/lutaml/model/serialize.rb:89:in `block (2 levels) in <module:ClassMethods>'
     # ./lib/xmi/sparx.rb:953:in `parse_xml'
     # ./spec/xmi/sparx/sparx_root_xmi2013_uml2013_spec.rb:10:in `block (4 levels) in <top (required)>'
     # ./spec/xmi/sparx/sparx_root_xmi2013_uml2013_spec.rb:40:in `block (4 levels) in <top (required)>'
```

**Comment by ronaldtse** [comment]
@kwkwan this has been fixed, can you please check?

**Comment by kwkwan** [comment]
The error has been checked and confirmed that it is fixed.  This issue will be closed.

**Comment by ronaldtse** [comment]
@kwkwan have we migrated from shale to lutaml-model?
